In [14]:
import pandas as pd 
import numpy as np

In [15]:
df = pd.read_csv("students.csv")
print(df.head())

   Unnamed: 0  Gender EthnicGroup          ParentEduc     LunchType TestPrep  \
0           0  female         NaN   bachelor's degree      standard     none
1           1  female     group C        some college      standard      NaN
2           2  female     group B     master's degree      standard     none
3           3    male     group A  associate's degree  free/reduced     none
4           4    male     group C        some college      standard     none

  ParentMaritalStatus PracticeSport IsFirstChild  NrSiblings TransportMeans  \
0             married     regularly          yes         3.0     school_bus
1             married     sometimes          yes         0.0            NaN
2              single     sometimes          yes         4.0     school_bus
3             married         never           no         1.0            NaN
4             married     sometimes          yes         0.0     school_bus

  WklyStudyHours  MathScore  ReadingScore  WritingScore
0            < 5         71            71            74
1         5 - 10         69            90            88
2            < 5         87            93            91
3         5 - 10         45            56            42
4         5 - 10         76            78            75

# Data Exploring & Pre-processing

In [16]:
df.describe()

         Unnamed: 0    NrSiblings     MathScore  ReadingScore  WritingScore
count  30641.000000  29069.000000  30641.000000  30641.000000  30641.000000
mean     499.556607      2.145894     66.558402     69.377533     68.418622
std      288.747894      1.458242     15.361616     14.758952     15.443525
min        0.000000      0.000000      0.000000     10.000000      4.000000
25%      249.000000      1.000000     56.000000     59.000000     58.000000
50%      500.000000      2.000000     67.000000     70.000000     69.000000
75%      750.000000      3.000000     78.000000     80.000000     79.000000
max      999.000000      7.000000    100.000000    100.000000    100.000000

In [27]:
df.head(10)

,Gender,EthnicGroup,ParentEduc,LunchType,TestPrep,ParentMaritalStatus,PracticeSport,IsFirstChild,NrSiblings,TransportMeans,WklyStudyHours,MathScore,ReadingScore,WritingScore
0,female,group C,bachelor's degree,standard,none,married,regularly,yes,3.000000,school_bus,< 5,71,71,74
1,female,group C,some college,standard,none,married,sometimes,yes,0.000000,school_bus,5 - 10,69,90,88
2,female,group B,master's degree,standard,none,single,sometimes,yes,4.000000,school_bus,< 5,87,93,91
3,male,group A,associate's degree,free/reduced,none,married,never,no,1.000000,school_bus,5 - 10,45,56,42
4,male,group C,some college,standard,none,married,sometimes,yes,0.000000,school_bus,5 - 10,76,78,75
5,female,group B,associate's degree,standard,none,married,regularly,yes,1.000000,school_bus,5 - 10,73,84,79
6,female,group B,some college,standard,completed,widowed,never,no,1.000000,private,5 - 10,85,93,89
7,male,group B,some college,free/reduced,none,married,sometimes,yes,1.000000,private,> 10,41,43,39
8,male,group D,high school,free/reduced,completed,single,sometimes,no,3.000000,private,> 10,65,64,68
9,female,group B,high school,free/reduced,none,married,regularly,yes,2.145894,private,< 5,37,59,50

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30641 entries, 0 to 30640
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           30641 non-null  int64
 1   Gender               30641 non-null  str
 2   EthnicGroup          28801 non-null  str
 3   ParentEduc           28796 non-null  str
 4   LunchType            30641 non-null  str
 5   TestPrep             28811 non-null  str
 6   ParentMaritalStatus  29451 non-null  str
 7   PracticeSport        30010 non-null  str
 8   IsFirstChild         29737 non-null  str
 9   NrSiblings           29069 non-null  float64
 10  TransportMeans       27507 non-null  str
 11  WklyStudyHours       29686 non-null  str
 12  MathScore            30641 non-null  int64
 13  ReadingScore         30641 non-null  int64
 14  WritingScore         30641 non-null  int64
dtypes: float64(1), int64(4), str(10)
memory usage: 5.6 MB

In [29]:
df.shape

(30641, 14)

# Data Reading & Dealing with null value

In [49]:
print(df.isnull().sum())

Gender                 0
EthnicGroup            0
ParentEduc             0
LunchType              0
TestPrep               0
ParentMaritalStatus    0
PracticeSport          0
IsFirstChild           0
NrSiblings             0
TransportMeans         0
WklyStudyHours         0
MathScore              0
ReadingScore           0
WritingScore           0
dtype: int64

In [ ]:
df['NrSiblings'] = df['NrSiblings'].fillna(df['NrSiblings'].mean())

print(df['NrSiblings'])

0        3.0
1        0.0
2        4.0
3        1.0
4        0.0
        ...
30636    2.0
30637    1.0
30638    1.0
30639    3.0
30640    1.0
Name: NrSiblings, Length: 30641, dtype: float64

# Drop unnamed column

In [18]:
df=df.drop("Unnamed: 0",axis = 1)
print(df.head())

   Gender EthnicGroup          ParentEduc     LunchType TestPrep  \
0  female         NaN   bachelor's degree      standard     none
1  female     group C        some college      standard      NaN
2  female     group B     master's degree      standard     none
3    male     group A  associate's degree  free/reduced     none
4    male     group C        some college      standard     none

  ParentMaritalStatus PracticeSport IsFirstChild  NrSiblings TransportMeans  \
0             married     regularly          yes         3.0     school_bus
1             married     sometimes          yes         0.0            NaN
2              single     sometimes          yes         4.0     school_bus
3             married         never           no         1.0            NaN
4             married     sometimes          yes         0.0     school_bus

  WklyStudyHours  MathScore  ReadingScore  WritingScore
0            < 5         71            71            74
1         5 - 10         69            90            88
2            < 5         87            93            91
3         5 - 10         45            56            42
4         5 - 10         76            78            75

In [31]:
df.head()

,Gender,EthnicGroup,ParentEduc,LunchType,TestPrep,ParentMaritalStatus,PracticeSport,IsFirstChild,NrSiblings,TransportMeans,WklyStudyHours,MathScore,ReadingScore,WritingScore
0,female,group C,bachelor's degree,standard,none,married,regularly,yes,3.0,school_bus,< 5,71,71,74
1,female,group C,some college,standard,none,married,sometimes,yes,0.0,school_bus,5 - 10,69,90,88
2,female,group B,master's degree,standard,none,single,sometimes,yes,4.0,school_bus,< 5,87,93,91
3,male,group A,associate's degree,free/reduced,none,married,never,no,1.0,school_bus,5 - 10,45,56,42
4,male,group C,some college,standard,none,married,sometimes,yes,0.0,school_bus,5 - 10,76,78,75

### It will check the duplicate row in data

In [41]:
df['Gender'].unique()

<ArrowStringArray>
['female', 'male']
Length: 2, dtype: str

### All column save in X feature except last column

In [36]:
x = df.iloc[:, :-1]
print(x)

       Gender EthnicGroup          ParentEduc     LunchType   TestPrep  \
0      female     group C   bachelor's degree      standard       none
1      female     group C        some college      standard       none
2      female     group B     master's degree      standard       none
3        male     group A  associate's degree  free/reduced       none
4        male     group C        some college      standard       none
...       ...         ...                 ...           ...        ...
30636  female     group D         high school      standard       none
30637    male     group E         high school      standard       none
30638  female     group C         high school  free/reduced  completed
30639  female     group D  associate's degree      standard  completed
30640    male     group B        some college      standard       none

      ParentMaritalStatus PracticeSport IsFirstChild  NrSiblings  \
0                 married     regularly          yes         3.0
1                 married     sometimes          yes         0.0
2                  single     sometimes          yes         4.0
3                 married         never           no         1.0
4                 married     sometimes          yes         0.0
...                   ...           ...          ...         ...
30636              single     sometimes           no         2.0
30637              single     regularly           no         1.0
30638             married     sometimes           no         1.0
30639             married     regularly           no         3.0
30640             married         never           no         1.0

      TransportMeans WklyStudyHours  MathScore  ReadingScore
0         school_bus            < 5         71            71
1         school_bus         5 - 10         69            90
2         school_bus            < 5         87            93
3         school_bus         5 - 10         45            56
4         school_bus         5 - 10         76            78
...              ...            ...        ...           ...
30636     school_bus         5 - 10         59            61
30637        private         5 - 10         58            53
30638        private         5 - 10         61            70
30639     school_bus         5 - 10         82            90
30640     school_bus         5 - 10         64            60

[30641 rows x 13 columns]

### just save last column in y

In [38]:
y = df.iloc[:, -1]
print(y)

0        74
1        88
2        91
3        42
4        75
         ..
30636    65
30637    51
30638    67
30639    93
30640    58
Name: WritingScore, Length: 30641, dtype: int64

In [20]:
df.mean(numeric_only=True)

NrSiblings       2.145894
MathScore       66.558402
ReadingScore    69.377533
WritingScore    68.418622
dtype: float64

In [21]:
df.mode(numeric_only=True)

   NrSiblings  MathScore  ReadingScore  WritingScore
0         1.0         64            65            67

In [16]:
df.median(numeric_only=True)

NrSiblings       2.0
MathScore       67.0
ReadingScore    70.0
WritingScore    69.0
dtype: float64

In [22]:
df = df.fillna(df.mean(numeric_only=True))

df = df.fillna(df.median(numeric_only=True))

df = df.fillna(df.mode().iloc[0])

# Check data type of columns

In [23]:
print(df.dtypes)

Gender                     str
EthnicGroup                str
ParentEduc                 str
LunchType                  str
TestPrep                   str
ParentMaritalStatus        str
PracticeSport              str
IsFirstChild               str
NrSiblings             float64
TransportMeans             str
WklyStudyHours             str
MathScore                int64
ReadingScore             int64
WritingScore             int64
dtype: object

# Education of parents

In [24]:
gb = df.groupby ("ParentEduc").agg({"MathScore": 'mean', "ReadingScore": "mean", "WritingScore" : "mean"})
print(gb)

                    MathScore  ReadingScore  WritingScore
ParentEduc
associate's degree  68.365586     71.124324     70.299099
bachelor's degree   70.466627     73.062020     73.331069
high school         64.435731     67.213997     65.421136
master's degree     72.336134     75.832921     76.356896
some college        66.445978     69.189667     68.456711
some high school    62.584013     65.510785     63.632409

# Impact of parent relationship on childern

In [25]:
gb1 = df.groupby ("ParentMaritalStatus").agg({"MathScore": 'mean', "ReadingScore": "mean", "WritingScore" : "mean"})
print(gb1)

                     MathScore  ReadingScore  WritingScore
ParentMaritalStatus
divorced             66.691197     69.655011     68.799146
married              66.650161     69.379561     68.406177
single               66.165704     69.157250     68.174440
widowed              67.368866     69.651438     68.563452

In [26]:
print(df["EthnicGroup"].unique())

<ArrowStringArray>
['group C', 'group B', 'group A', 'group D', 'group E']
Length: 5, dtype: str

## Converting Datatype into int

In [50]:
df['NrSiblings'] = df['NrSiblings'].astype(int)

print(df['NrSiblings'].dtype)

int64

In [51]:
cat_columns = df.select_dtypes(['object']).columns

df[cat_columns] = df[cat_columns].apply(lambda x: pd.factorize(x)[0])

print(df.head())

C:\Users\A.s\AppData\Local\Temp\ipykernel_1192\4110118952.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_columns = df.select_dtypes(['object']).columns

   Gender  EthnicGroup  ParentEduc  LunchType  TestPrep  ParentMaritalStatus  \
0       0            0           0          0         0                    0
1       0            0           1          0         0                    0
2       0            1           2          0         0                    1
3       1            2           3          1         0                    0
4       1            0           1          0         0                    0

   PracticeSport  IsFirstChild  NrSiblings  TransportMeans  WklyStudyHours  \
0              0             0           3               0               0
1              1             0           0               0               1
2              1             0           4               0               0
3              2             1           1               0               1
4              1             0           0               0               1

   MathScore  ReadingScore  WritingScore
0         71            71            74
1         69            90            88
2         87            93            91
3         45            56            42
4         76            78            75

In [52]:
x = df.iloc[:, 0:-1]

y = df.iloc[:, -1]

print(x.shape)
print(y.shape)

(30641, 13)
(30641,)